### ISSUE TITLE
Projeto Parte I - FrontEnd

### ISSUE THREAD

**Issue by analia929** [joyceMiranda/webClasses#1]
Olá, para  o Projeto Parte I - FrontEnd, pode ser usado algum tipo de framework?

**Comment by joyceMiranda** [comment]
Olá Anália,

A ideia do Projeto Parte I é exercitar o conteúdo visto em sala de aula na
criação do front-end do site.
Se usar um framework, a tendência é que ele gere quase todo o código.
Por isso, não aconselho o uso do framework nessa parte do projeto.

Em 29 de fevereiro de 2016 19:48, Anália Oliveira notifications@github.com
escreveu:
